### ISSUE TITLE
VideoSink-VideoPublishingOptions : DisableRtspPublishing set to true still makes widget enter Live-mode

### ISSUE THREAD

**Issue by chokosticks** [Azure/video-analyzer#100]
Hi,

I've been testing cloud pipelines and the sample topology: Live capture, record, and stream from RTSP camera behind firewall

When setting DisableRtspPublishing-setting to true on the videoSink the excepted behavior is to disable the widget to enter Live-mode because the low-latency rtsp-url is not published.

When the pipeline is active, the video-analyzer widget still goes into "Live"-mode. 

Is there another way to disable Live-mode on the video analyzer or video analyzer widget?

Regards

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
