### ISSUE TITLE
Is this Repo is working or not

### ISSUE THREAD

**Issue by manish0079** [Azure/video-analyzer#101]
I m trying to build  a docker file from this repo locally and want to do inference,I built the docker image and ran the container but while testing in POST Method it is throwing **502  bad gateway error**

But at the same time, I ran the image from the MCR (**docker run --name my_yolo_container -p 8080:80 -d -i mcr.microsoft.com/ava-utilities/avaextension:http-yolov3-onnx-v1.0**) it is working 

Can anyone help me to figure out, Is the repository is not updated, or can you help me in sharing the MCR repo

Thank you

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
