### ISSUE TITLE
Updated topology file for OpenVINO DL Streamer Extension

### ISSUE THREAD

**Issue by nnshah1** [Azure/video-analyzer#25]
@nicolasbotto,  For the topology file:

https://github.com/Azure/video-analyzer/blob/main/pipelines/live/topologies/grpcExtensionOpenVINO/topology.json 

We recommend removing scaling from the topology as we have done here:

https://github.com/intel/video-analytics-serving/blob/v0.5.2.beta-dev/samples/lva_ai_extension/topologies/topology.json 

Otherwise this toplogy can result in invalid inferences as the frame will be scaled twice - please sections:

https://github.com/Azure/video-analyzer/blob/6b0b6acf8009821d35e98512706e267348f311cc/pipelines/live/topologies/grpcExtensionOpenVINO/topology.json#L100

https://github.com/Azure/video-analyzer/blob/6b0b6acf8009821d35e98512706e267348f311cc/pipelines/live/topologies/grpcExtensionOpenVINO/topology.json#L55

https://github.com/Azure/video-analyzer/blob/6b0b6acf8009821d35e98512706e267348f311cc/pipelines/live/topologies/grpcExtensionOpenVINO/topology.json#L61

and 

https://github.com/Azure/video-analyzer/blob/6b0b6acf8009821d35e98512706e267348f311cc/pipelines/live/topologies/grpcExtensionOpenVINO/topology.json#L49 

would need to be removed

**Comment by naiteeks** [comment]
Closing issue as the PR with the fix is now merged.

**Comment by nnshah1** [comment]
@naiteeks Thanks!
