### ISSUE TITLE
AVA on Azure Stack Edge GPU

### ISSUE THREAD

**Issue by dennisfelczy** [Azure/video-analyzer#30]
Is there a new documentation about the necessary steps/adjustments to run AVA on Azure Stack Edge ? similar to:
[LVA on Stack Edge](https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/deploy-azure-stack-edge-how-to#:~:text=%20Configuring%20Azure%20Stack%20Edge%20for%20using%20Live,final%20step%20is%20to%20ensure%20that...%20More%20)

The module works for some time but then goes down sometimes with Error Code 139 sometimes without Error Code. I already created Mounts for /var/media and /var/lib/videoanalyzer in the Device Twin but it does not seem to fix the issue.

**Comment by naiteeks** [comment]
Hi @dennisfelczy  - that document is in the works and should be available soon. I will updated this thread with the link once the doc is published.

**Comment by naiteeks** [comment]
Hi @dennisfelczy  - here are the steps to [Deploy Azure Video Analyzer on ASE device](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/deploy-on-stack-edge).
