### ISSUE TITLE
Offline Support of Solution

### ISSUE THREAD

**Issue by kristopherjturner** [Azure/video-analyzer#49]
Our customers range from DOD to USDA to National Institution for Health (NIH) and more.  Most of our use cases for deploying edge solutions will require those devices to be offline for a period of time.  For production deployments, the short window that is currently set won't work for most of our use cases.  We like the product and see good use of the solution for various customers but unless the offline support time range is extended or somehow designed to run fully offline we can't deploy this solution to a majority of our projects.  Even if the offline time was a minimum of 72 hours this may work. Preferably it would be good to see this solution set up to run offline for a few weeks as well.  A perfect case in hand is the 82nd Airbourne and their immediate response team was just deployed to Afghanistan to assist in the evacuation of the embassy.  The ASE devices they will have deployed could use some of these features but since they are deployed will have very limited connectivity for the few weeks they are deployed.

**Comment by anilmur** [comment]
We've noted the feature request - will take the discussion offline for our planning efforts.
