### ISSUE TITLE
USB-to-RTSP not working on Linux arm64

### ISSUE THREAD

**Issue by sherazfaisal** [Azure/video-analyzer#51]
Hi there,

I hope you are doing good, I have been trying to convert my USB camera feed to RTSP for over a month. I haven't figured out any suitable way of doing that. I am using Linux arm64 OS in Raspberry Pi 4 (4 GB RAM). I have followed the steps given in  https://github.com/Azure/video-analyzer/tree/main/edge-modules/sources/USB-to-RTSP . Everything go smoothly without any errors. When I run the main docker file it is supposed to convert USB camera feed to RTSP but it doesn't do it. I can't seem to access the output 'rtsp://127.0.0.1/stream1' inside VLC or any other streaming platform. I have tried my best to ensure every step followed correctly. I haven't seen any results. When I tried to make it work on my PC (OS Linux amd64), it actually works. I haven't figured out the solution to this issue. I would need your help in this regard. It's an urgency. I need to make my AI solution work inside Raspberry Pi. I am using Azure Video Analyzer which only supports RTSP streams. Kindly educate me if there is a way to make my USB camera stream work with Azure Video Analyzer. 

Regards
Sheraz Faisal
muhammad.sheraz@hypernymbiz.com

**Comment by russell-cooks** [comment]
Hi @sherazfaisal , could you provide us with the logs from your terminal, so that we can look further into this?

**Comment by sherazfaisal** [comment]
Hi @russell-cooks,

I am replying late because I wanted to make sure I have done every possible thing to make it work. It doesn't seem to work on Linux arm64 (Raspberry Pi). I am attaching the following screenshots of all the steps I have made.

![0](https://user-images.githubusercontent.com/70267504/133961046-73ce7f80-aaac-4e13-9aef-932d7aeeed20.png)
![1](https://user-images.githubusercontent.com/70267504/133961056-7f4ab9bf-bff3-4ae9-9e96-3d71f96ceb0e.png)
![2](https://user-images.githubusercontent.com/70267504/133961052-351e0884-3bc4-4339-bf2d-64fc56d76b9f.png)
![4](https://user-images.githubusercontent.com/70267504/133961054-7046e839-1845-4736-a781-f8d0be608804.png)
![5](https://user-images.githubusercontent.com/70267504/133961050-2a850380-a59d-4a97-b361-5e406c48c0c1.png)
![6](https://user-images.githubusercontent.com/70267504/133961049-fe08187c-eca3-417c-9de8-66e5369cc6f7.png)

I hope you would be able to find any solution to this issue. Thank you for your cooperation

Regards
Sheraz Faisal
muhammad.sheraz@hypernymbiz.com

**Comment by russell-cooks** [comment]
Hi @sherazfaisal,

Apologies for the delayed response.
It seems that you followed the steps correctly.

Could you run "sudo docker logs usb-to-rtsp" and provide the results?

**Comment by sherazfaisal** [comment]
Hi @russell-cooks 

I have followed the same steps and extracted the logs using "sudo docker logs usb-to-rtsp". Here are the results.

![image](https://user-images.githubusercontent.com/70267504/135836233-b3d84fd1-8122-4887-b853-4a07db3344df.png)

**Comment by russell-cooks** [comment]
Hi @sherazfaisal,

Thank you. I was expecting to see an error here. I will have to do some further investigation. Please ensure that you are using the correct RTSP URL when testing with VLC, as I see in your screenshot that you were testing 192.168.137.61.

**Comment by sherazfaisal** [comment]
Hi @russell-cooks,

I wanted to let you know that I am using Ubuntu Server 20.04. I can't use VLC player on the same device. So I have used VLC player in other device connected to the same network. I make sure the RTSP URL is correct. It is in the format explained below.
rtsp://<IP-ADDRESS-LINUX-ARM64-DEVICE>/stream1 
Please let me know if you find any solution to this issue.  Thank you

**Comment by russell-cooks** [comment]
@sherazfaisal We are looking into this issue. We would like to understand the reasoning behind your use of Ubuntu Server 20.04 on the Raspberry Pi, if you could please explain. Thank you.

**Comment by sherazfaisal** [comment]
@russell-cooks We wanted an easy interface for installation of Azure IoT Edge and Azure IoT Hub and bash Scripting. Please let us know if you could find any workaround to this issue. Thanks

**Comment by russell-cooks** [comment]
@sherazfaisal Ok thank you for the response. We have someone testing out the scenario on a Raspberry Pi, and we will follow up with you on the outcome. Thank you for your patience.

**Comment by jasonxian-msft** [comment]
Hi @sherazfaisal, thank you for patiently waiting on this. I have validated your scenario on Ubuntu server 20.04 running on Raspberry Pi. Running the Docker container above works. I think the key to making your solution work is verifying the IP address of your Raspberry Pi.

To get the IP address, please type `ifconfig` into a terminal and obtain the private IP address that looks like this: `inet 192.168.1.238`

Next, run the Docker container on your Raspberry Pi. On another machine on the same local network, use either of the following RTSP URLs.

`rtsp://192.168.1.238:554/stream1`

`rtsp://192.168.1.238/stream1`

If you obtained the IP address correctly, another troubleshooting step is to check the port binding when running the Dockerfile. Notice that port 8554 is exposed per the Dockerfile, and that is mapped to the Raspberry Pi's port 554. (Port 554 is typically exposed for RTSP streaming.)
