### ISSUE TITLE
Tutorial: Record and stream inference metadata with video

### ISSUE THREAD

**Issue by Ilheu** [Azure/video-analyzer#58]
I'm trying to implement this tutorial with Visual Studio Code AVA extension:
https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/record-stream-inference-data-with-video

In which you show this schematic:
![image](https://user-images.githubusercontent.com/8053606/135626890-4fae2863-5454-4d80-9952-7227a8df7fa3.png)

So I tried to implement it, but 2 errors ocurred: **(There are no matching media types between nodes 'objectTrackingProcessor' and 'videoSink')**

![image](https://user-images.githubusercontent.com/8053606/135627097-98b02a30-212e-47a1-827e-9152d525c948.png)

I read in this document that Video Sink has limitations: "**Must be immediately downstream from RTSP source or signal gate processor.**"

https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/quotas-limitations

 So it is not possible to link Video Sink and Object Tracker like you said?

**Comment by KishorIoT** [comment]
There is no video from object tracker, it can inference or metadata.  if you remove video between object tracker & video sink this will work.. 
![image](https://user-images.githubusercontent.com/39635218/135688439-842a222a-45e2-466c-9a2f-60a6325afcd5.png)

**Comment by Ilheu** [comment]
you right! But I can not watch the video.
![image](https://user-images.githubusercontent.com/8053606/135863772-59b718a5-3045-4580-90a9-93a58167183b.png)
Do you have any idea?

**Comment by KishorIoT** [comment]
Could you share more detail on where you see this issue, this is based on https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/record-stream-inference-data-with-video ??

Thanks
-Kishor

**Comment by KishorIoT** [comment]
also could you remove video in your object tracker to video sinc output type ?

![image](https://user-images.githubusercontent.com/39635218/135930817-69e8a693-e9fa-4fe0-abff-b6d7710ae171.png)

there is no video from object tracker refer to following snippet 
![image](https://user-images.githubusercontent.com/39635218/135930970-0740a596-b8c6-4026-b8a9-575f626ef8f4.png)

**Comment by KishorIoT** [comment]
Glad we could help. Keep us updated on the progress, and let us know if you need anything from the product team.

Thanks
-Kishor

**Comment by naiteeks** [comment]
Closing this issue. Thank you @KishorIoT .
