### ISSUE TITLE
Video Analyzer: Motion detection within Zones.

### ISSUE THREAD

**Issue by chokosticks** [Azure/video-analyzer#59]
Hi, 

I am trying out Video Analyzer on IoT Edge. 
Is it possible to specify a zone for motion detection?  

I.e. construct a pipeline which records and creates events on motion detection within the specified zone.

Or is it planned as a feature in the future?

**Comment by jasonxian-msft** [comment]
Hi @dahlinius, your scenario sounds a bit like what's supported in our zone drawer sample. Have you checked out this how-to guide yet? 

Zone drawer sample: https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/sample-player-widget#zone-drawer

**Comment by chokosticks** [comment]
Hi @jasonxian-msft, 

Thanks for the quick reply.

From what I can tell there's a possibility to draw the zone, but I haven't found a way to actually use this zone in a pipelineTopology on the Azure Video Analyzer-module. Where I create a pipeline and on motion detection within this zone, start the recording using a signal gate processor or some other node.

Is there a setup of nodes that could use this zone we create?

**Comment by jasonxian-msft** [comment]
Hi @dahlinius, after drawing the polygon on the zone-drawer, you can use the line-crossing pipeline topology to add the polygon to your model. On lines 125 to 130, you can specify the following:
- Type: "#Microsoft.VideoAnalyzer.NamedLineString" or "#Microsoft.VideoAnalyzer.NamedPolygonString"
- Name
- Line or polygon: the coordinates are filled in using the `${lineCoordinates}` placeholder, but you can alter this by pasting in your coordinates based on the zone-drawer widget.

Link for topology: https://github.com/Azure/video-analyzer/blob/main/pipelines/live/topologies/line-crossing/topology.json 

Link for example coordinates for line or polygon: https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/sample-player-widget#zone-drawer

**Comment by chokosticks** [comment]
Thanks for the detailed answer. I'll give it a try.

I got one more question. In my scenario I'm not only looking to get a recording when an object crosses a line in/out from the polygon-zone, but also when an object is making motion inside of the polygon-zone. Is this possible with the suggested setup?

**Comment by jasonxian-msft** [comment]
Correct, the solution I provided above will only provide an inference once an object crosses the zone once. To get motion detection inside the polygon-zone, we have some options:

- We are developing a node that enables this feature. It is scheduled for release at the end of November 2021.
- You can create your own motion detection model and add zones in the model, then use the HTTP extension or gRPC extension to connect with AVA.

Outside of motion detection, we offer a tutorial on using spatial analysis. This will allow you to see inferences for spatial relationships between people and movement in physical space. We have an ability to add zones in this model, but you'll need hardware with Nvidia Tesla T4 GPU.

https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/computer-vision-for-spatial-analysis?tabs=virtual-machine

**Comment by chokosticks** [comment]
Thanks.

If you guys need some early adopter for the new node you're developing, sign me up.
I'll take a look at developing my own motion detection model.

Thanks for the support.
