### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by Ilheu** [Azure/video-analyzer#60]
I was following your readme setps, but I think it should be Dockerfile instead of yolo3.dockerfile. 

https://github.com/Azure/video-analyzer/tree/main/edge-modules/extensions/yolo/yolov3/grpc-cpu

![image](https://user-images.githubusercontent.com/8053606/136240063-581b4e38-1956-4912-bef7-6387d9bf71de.png)

**Comment by jasonxian-msft** [comment]
Thanks for raising this to us!

**Comment by jasonxian-msft** [comment]
Are you trying to run this tutorial? 

https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/analyze-live-video-use-your-model-grpc?pivots=programming-language-csharp

**Comment by jasonxian-msft** [comment]
Hi @Ilheu, it seems we were using an older version of the gRPC model on the Python samples. When the latest one is pushed over, I'll notify you again.

**Comment by Ilheu** [comment]
**Sorry, that error logs are from this:

https://github.com/Azure/video-analyzer/tree/main/edge-modules/extensions/yolo/yolov3/grpc-cpu

I'm trying to add a simple yolov3 module to my azure iot edge, but it gives me these errors**

[AVAX] [2021-10-06 17:18:36,626] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 27
Line: self._shmFile = open(self._shmFileFullPath, 'r+b')
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:36,627] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/inference_engine.py
Line number: 46
Line: self._sharedMemoryManager = SharedMemoryManager(
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:36,627] [ThreadPoolEx] [ERROR]: Exception iterating responses: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
return next(response_iterator), True
File "/avaextension/inference_engine.py", line 186, in ProcessMediaStream
clientState = State(mediaStreamMessageRequest.media_stream_descriptor)
File "/avaextension/inference_engine.py", line 46, in init
self._sharedMemoryManager = SharedMemoryManager(
File "/avaextension/shared_memory.py", line 27, in init
self._shmFile = open(self._shmFileFullPath, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:36,628] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 105
Line: self._shmFile.close()
Value: 'SharedMemoryManager' object has no attribute '_shmFile'
Exception ignored in: <function SharedMemoryManager.del at 0x7f273500bf70>
Traceback (most recent call last):
File "/avaextension/shared_memory.py", line 105, in del
self._shmFile.close()
AttributeError: 'SharedMemoryManager' object has no attribute '_shmFile'
[AVAX] [2021-10-06 17:18:46,683] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 27
Line: self._shmFile = open(self._shmFileFullPath, 'r+b')
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:46,684] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/inference_engine.py
Line number: 46
Line: self._sharedMemoryManager = SharedMemoryManager(
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:46,684] [ThreadPoolEx] [ERROR]: Exception iterating responses: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
return next(response_iterator), True
File "/avaextension/inference_engine.py", line 186, in ProcessMediaStream
clientState = State(mediaStreamMessageRequest.media_stream_descriptor)
File "/avaextension/inference_engine.py", line 46, in init
self._sharedMemoryManager = SharedMemoryManager(
File "/avaextension/shared_memory.py", line 27, in init
self._shmFile = open(self._shmFileFullPath, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:46,684] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 105
Line: self._shmFile.close()
Value: 'SharedMemoryManager' object has no attribute '_shmFile'
Exception ignored in: <function SharedMemoryManager.del at 0x7f273500bf70>
Traceback (most recent call last):
File "/avaextension/shared_memory.py", line 105, in del
self._shmFile.close()
AttributeError: 'SharedMemoryManager' object has no attribute '_shmFile'
[AVAX] [2021-10-06 17:18:56,659] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 27
Line: self._shmFile = open(self._shmFileFullPath, 'r+b')
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:56,659] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/inference_engine.py
Line number: 46
Line: self._sharedMemoryManager = SharedMemoryManager(
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:56,660] [ThreadPoolEx] [ERROR]: Exception iterating responses: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
return next(response_iterator), True
File "/avaextension/inference_engine.py", line 186, in ProcessMediaStream
clientState = State(mediaStreamMessageRequest.media_stream_descriptor)
File "/avaextension/inference_engine.py", line 46, in init
self._sharedMemoryManager = SharedMemoryManager(
File "/avaextension/shared_memory.py", line 27, in init
self._shmFile = open(self._shmFileFullPath, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:18:56,661] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 105
Line: self._shmFile.close()
Value: 'SharedMemoryManager' object has no attribute '_shmFile'
Exception ignored in: <function SharedMemoryManager.del at 0x7f273500bf70>
Traceback (most recent call last):
File "/avaextension/shared_memory.py", line 105, in del
self._shmFile.close()
AttributeError: 'SharedMemoryManager' object has no attribute '_shmFile'
[AVAX] [2021-10-06 17:19:06,698] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 27
Line: self._shmFile = open(self._shmFileFullPath, 'r+b')
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:19:06,698] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/inference_engine.py
Line number: 46
Line: self._sharedMemoryManager = SharedMemoryManager(
Value: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:19:06,698] [ThreadPoolEx] [ERROR]: Exception iterating responses: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/grpc/_server.py", line 461, in _take_response_from_response_iterator
return next(response_iterator), True
File "/avaextension/inference_engine.py", line 186, in ProcessMediaStream
clientState = State(mediaStreamMessageRequest.media_stream_descriptor)
File "/avaextension/inference_engine.py", line 46, in init
self._sharedMemoryManager = SharedMemoryManager(
File "/avaextension/shared_memory.py", line 27, in init
self._shmFile = open(self._shmFileFullPath, 'r+b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/inference_client_share_memory_12657654825598363479'
[AVAX] [2021-10-06 17:19:06,700] [ThreadPoolEx] [INFO]: Exception:
File name: /avaextension/shared_memory.py
Line number: 105
Line: self._shmFile.close()
Value: 'SharedMemoryManager' object has no attribute '_shmFile'
Exception ignored in: <function SharedMemoryManager.del at 0x7f273500bf70>
Traceback (most recent call last):
File "/avaextension/shared_memory.py", line 105, in del
self._shmFile.close()
AttributeError: 'SharedMemoryManager' object has no attribute '_shmFile'
