### ISSUE TITLE
Extract Video Frames

### ISSUE THREAD

**Issue by Ilheu** [Azure/video-analyzer#64]
I performed the following tutorial (https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/develop-deploy-grpc-inference-srv), but I would like to have access to some frames of the video that I am dealing with in my algorithm. 
Is it possible? I saw that there is the variable Debug but it is not used in the code that you provide. I would love to access to save some local files.

**Comment by anilmur** [comment]
@Ilheu  - can this issue be closed now?

**Comment by Ilheu** [comment]
@anilmur Yes it can, thank you for the support!
