### ISSUE TITLE
Cannot get AVA working in IoT Edge Simulator - System.ArgumentNullException

### ISSUE THREAD

**Issue by XavierGeerinck** [Azure/video-analyzer#76]
For development purposes we would like to use AVA in the IoT Edge Simulator (iotedgehubdev) but are encountering some issues. After finally being able to start it (we had to remove the Binds for example since iotedgehubdev doesn't support them) we got the following crash:

```bash
avaedge       | Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
avaedge       |    at System.Text.Encoding.GetBytes(String s)
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Common.Utilities.StableHash.GetStableHash(String input)
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.DataIntegrityEnforcer.EnsureApplicationDirectoryDataIsValidAsync()
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Core.MediaEdgeModule.InitializeAsync()
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Common.Hosts.IoTEdge.EdgeHost.SetModuleAsync(IEdgeModule module)
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.Main(String[] args)
avaedge       |    at Microsoft.Media.LiveVideoAnalytics.Edge.Modules.MediaEdge.Hosts.IoTEdge.Program.<Main>(String[] args)
```

There is a parameter not set, but we are not sure which one :) could anyone help us with this? The following are the properties that we put in the module twin:

```json
{
            "applicationDataDirectory": "/var/lib/videoanalyzer",
            "provisioningToken": "MASKED",
            "diagnosticsEventsOutputName": "diagnostics",
            "operationalEventsOutputName": "operational",
            "logLevel": "information",
            "LogCategories": "Application,Events",
            "allowUnsecuredEndpoints": true,
            "telemetryOptOut": false,
}
```

**Comment by anilmur** [comment]
The method EnsureApplicationDirectoryDataIsValidAsync is checking the value of applicationDataDirectory. Presume you are aware of how [docker ](https://docs.docker.com/storage/) handles application data when there are no binds. In your case you are providing a valid string for applicationDataDirectory - I wonder if this is something to do with the edge simulator. I'll see if I can get any tips from engineering.

**Comment by anilmur** [comment]
@XavierGeerinck - please reach out to videoanalyzerhelp@microsoft.com if you wish to discuss this further. Currently, we are not validating the Video Analyzer edge module on the IoT Edge Simulator. Thanks
