### ISSUE TITLE
Provisioning token for multiple devices

### ISSUE THREAD

**Issue by bkarrlander** [Azure/video-analyzer#81]
Hi,

We will be deploying the Video Analyzer module on hundreds of IoT Edge devices. Do we have to create one edge module entry (and its accompanying provisioning token) for each of these devices in the Video Analyzer settings? Or can we use the same provisioning token for all devices? 

Best regards,
Björn

**Comment by russell-cooks** [comment]
Hi @bkarrlander,

You would need to create an edge module entry for each device.

**Comment by bkarrlander** [comment]
@russell-cooks, thanks for your response.

Is there any guidance written for deploying Video Analyzer at the edge on scale?

Regards,
Björn

**Comment by russell-cooks** [comment]
@bkarrlander  We do not have any general customer-facing guidance as of right now, but it is in the works.
If there is a specific ask, please let us know.

**Comment by bkarrlander** [comment]
Ok, @russell-cooks, sounds good. Do you know if there is a way to programmatically create those edge module entries?

**Comment by russell-cooks** [comment]
Hi @bkarrlander, apologies for the delayed response. Here is an article from IoT Edge about deploying IoT Edge modules at scale: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-at-scale?view=iotedge-2020-11 

We currently do not have a way to programmatically create or query edge module entries for Azure Video Analyzer.

**Comment by bkarrlander** [comment]
@russell-cooks, thanks for your response.

regards,
Björn

**Comment by russell-cooks** [comment]
Hi @bkarrlander, 
Apologies, here is a link to the operations available for creating and managing edge module entries with our REST API.

**Comment by bkarrlander** [comment]
@russell-cooks, that's awesome. Just tried it out for our purposes and it worked like a charm. 

Thanks,
Björn

**Comment by russell-cooks** [comment]
@bkarrlander Great! Here is a Postman sample that we have published that might be helpful with making the API requests
https://github.com/Azure-Samples/video-analyzer-postman

**Comment by bkarrlander** [comment]
@russell-cooks, excellent! Thanks

Regards,
Björn
