### ISSUE TITLE
Viewing video recordings in Video Analyzer should still show the timeline when recording has stopped

### ISSUE THREAD

**Issue by mattcowen** [Azure/video-analyzer#86]
I'm running the quickstart [here](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/edge/detect-motion-record-video-clips-cloud). When viewing the video for a live pipeline you see the segments of recorded video in the timeline and can easily navigate as shown below.

![image](https://user-images.githubusercontent.com/7049239/143765120-ec91b895-646b-4058-a003-b51318bd300a.png)

When the pipeline has stopped and the status is "Not Recording", viewing the video no longer shows the segments on the timeline so I'm unable to distinguish where in the timeline events happened.

![image](https://user-images.githubusercontent.com/7049239/143765196-74e88840-3725-47c1-ada4-e9445feaa098.png)

**Comment by nikitapitliya** [comment]
Hi @mattcowen, Thanks for raising the issue. It is indeed a bug and we are working to resolve this issue. I'll keep you posted with the resolution timeline.

**Comment by nikitapitliya** [comment]
Hi @mattcowen - As discussed offline, the fix for this bug has been released. Please verify you can see the segments on the timeline in a recorded video. Let me know if you see any discrepancies.

**Comment by naiteeks** [comment]
@mattcowen  - closing the issue due to inactivity. Please feel free to re-open if the issue persists.
