### ISSUE TITLE
VideoSink should store video to LocalMediaCachePath when internet connectivity is lost

### ISSUE THREAD

**Issue by mattcowen** [Azure/video-analyzer#87]
When specifying the localMediaCachePath as below, I am not seeing any videos saved when the edge device loses Internet connectivity. Edge device is an Azure Stack Edge Mini-R. When connectivity is restored, video is being recorded to the Video Analyzer storage account.

```
          {
              "@type": "#Microsoft.VideoAnalyzer.VideoSink",
              "localMediaCachePath": "/var/lib/videoanalyzer/tmp",
              "localMediaCacheMaximumSizeMiB": "2048",
              "videoName": "motion-with-multiple-grpc-extensions",
              "videoCreationProperties": {
                  "title": "motion-with-multiple-grpc-extensions",
                  "description": "Sample video using motion with gRPC extension",
                  "segmentLength": "PT30S"
              },
              "name": "videoSink",
              "inputs": [
                  {
                      "nodeName": "signalGateProcessor",
                      "outputSelectors": [
                          {
                              "property": "mediaType",
                              "operator": "is",
                              "value": "video"
                          }
                      ]
                  }
              ]
          }
```
I verified the avaedge container has a bind for /var/lib/videoanalyzer which is to /media/appdata and tmp exists.

Mounts:
      /var/lib/videoanalyzer from mediaappdata (rw)

What could I be missing?

**Comment by nikitapitliya** [comment]
Hi @mattcowen - The "localMediaCachePath" behaves as expected when tested on Azure VM used as an edge device. As discussed offline, please raise a support ticket for ASE device and feel free to loop the AVA PM team on it. 

I am closing this issue for now, please reopen if you need further assistance.
