### ISSUE TITLE
No ARMV7 Manifest for Video Analyzer

### ISSUE THREAD

**Issue by nimanch** [Azure/video-analyzer#91]
Hi, 
When I try to deploy AVA Module to my IoT Edge Device (ARMV7 Ubuntu 20.04). I get this error

 Could not create module avaedge
        caused by: Could not pull image mcr.microsoft.com/media/video-analyzer:latest
        caused by: no matching manifest for linux/arm/v7 in the manifest list entries

Is ARMV7 Supported?

**Comment by jasonxian-msft** [comment]
Hi @nimanch, the avaedge module is only supported on ARM64 and x64 architectures.
