### ISSUE TITLE
"This video is not ready for playback right now" after video deletion and recreation

### ISSUE THREAD

**Issue by dm-s360** [Azure/video-analyzer#96]
We are doing some RTSP recording on the edge with Azure Video Analyzer.

Today we noticed that the ava edge module threw continuous errors of type "Microsoft.VideoAnalyzer.Diagnostics.VideoFormatError".
Because we couldn't identify any cause, we deleted the entire video reference via the Azure Portal.
After this we recreated pipelines and restarted recording. The edge module error is now resolved and it seems to be recording just fine. Files are being added on storage.

However, when trying to watch the video in the player (also via the Azure Portal), we always get the message: 
"This video is not ready for playback right now, Check whether your live pipeline is in an active state and is connected to the RTSP camera" although the actual status of the video is "Recording" and it has been recording for several minutes.

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
