### ISSUE TITLE
Need option to set timezone for the video player

### ISSUE THREAD

**Issue by dm-s360** [Azure/video-analyzer#97]
Currently all timings in the player are UTC, which makes the timeline and time-container pretty useless.

We need to have an option to configure the users timezone to have the timings adjusted accordingly.

**Comment by jasonxian-msft** [comment]
Hello,

This repository is no longer being maintained. 

We’re retiring the Azure Video Analyzer preview service, you're advised to transition your applications off of Video Analyzer by December 01, 2022.

Action Required: To minimize disruption to your workloads, transition your application from Video Analyzer per suggestions described in this [guide](https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/transition-from-video-analyzer) before December 01, 2022. After December 01, 2022 your Azure Video Analyzer account will no longer function.
